export const SEARCH_HERO_REQUEST = "SEARCH_HERO_REQUEST";
export const SEARCH_HERO_SUCCESS = "SEARCH_HERO_SUCCESS";
export const SEARCH_HERO_ERROR = "SEARCH_HERO_ERROR";

export const SEARCH_DETAILS_HERO_REQUEST = "SEARCH_DETAILS_HERO_REQUEST";
export const SEARCH_DETAILS_HERO_SUCCESS = "SEARCH_DETAILS_HERO_SUCCESS";
export const SEARCH_DETAILS_HERO_ERROR = "SEARCH_DETAILS_HERO_ERROR";

export const ALL_HEROS_REQUEST = "ALL_HEROS_REQUEST";
export const ALL_HEROS_SUCCESS = "ALL_HEROS_SUCCESS";
export const ALL_HEROS_ERROR = "ALL_HEROS_ERROR";

export const NEW_HERO_REQUEST = "NEW_HERO_REQUEST";
export const NEW_HERO_SUCCESS = "NEW_HERO_SUCCESS";
export const NEW_HERO_RESET = "NEW_HERO_RESET";
export const NEW_HERO_ERROR = "NEW_HERO_ERROR";

export const HERO_DETAILS_REQUEST = "HERO_DETAILS_REQUEST";
export const HERO_DETAILS_SUCCESS = "HERO_DETAILS_SUCCESS";
export const HERO_DETAILS_ERROR = "HERO_DETAILS_ERROR";

export const DELETE_HERO_REQUEST = "DELETE_HERO_REQUEST";
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS";
export const DELETE_HERO_RESET = "DELETE_HERO_RESET";
export const DELETE_HERO_ERROR = "DELETE_HERO_ERROR";


export const CLEAR_ERRORS = "CLEAR_ERRORS";